### ISSUE TITLE
Dynamic reconfigure for python

### ISSUE THREAD

**Issue by AlexReimann** [pyros-dev/ros1_template#15]

**Comment by asmodehn** [comment]
[dynamic_reconfigure](https://github.com/ros/dynamic_reconfigure) for pytemplate
[dynamic_dynamic_reconfigure](https://github.com/pal-robotics/ddynamic_reconfigure_python) for pip_pytemplate

**Comment by asmodehn** [comment]
dynamic_reconfigure in progress in https://github.com/pyros-dev/ros1_template/pull/20

**Comment by asmodehn** [comment]
dynamic_dynamic_reconfigure doesnt seem really active or accepted yet, mostly because of lack of C++ implementation ( https://github.com/ros/dynamic_reconfigure/issues/62 )

Maybe we shouldn't put that in this template until it gets integrated in dynamic_reconfigure...

The plan was to dynamically add different arguments for httpbin / ros1_pip_pytemplate... instead we can maybe use dynamic_reconf and use a list of args...

**Comment by asmodehn** [comment]
dynamic_reconfigure has been done. Lets close this and treat the rest as different issues.
